server:
  port: 8083

spring:
  application:
    name: statement
  zipkin:
    base-url: http://zipkin:9411
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    instance:
      preferIpAddress: true
    enabled: false
