apiVersion: apps/v1
kind: Deployment
metadata:
  name: marital
  labels:
    app: marital
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marital
  template:
    metadata:
      name: marital
      labels:
        app: marital
    spec:
      containers:
        - name: marital
          image: greg94/marital-status:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always

