server:
  port: 8082

spring:
  application:
    name: marital
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    instance:
      preferIpAddress: true